### ISSUE TITLE
AudioSource interface

### ISSUE THREAD

**Issue by danpovey** [pzelasko/lhotse#4] opened 2020-04-26 13:01 UTC
I get the impression that the AudioSource interface might assume that different channels will be located in different files?  In general this won't be the case, often multiple channels will be interleaved in one file, like in the wav format.

@jtrmal please comment on this next, larger issue:

I think maybe the AudioSet interface, and its dependencies, are too concrete.  Or at least there should be a more abstract version of it somewhere, that is intended to be overloaded.  Issues include:
  - We might at some point want to have some kind of dynamically created AudioSet where we add noise and/or reverberation.  We could use an AudioSet child class that does reverberation and takes the base AudioSet as a constructor arg.  Similarly for duplicating and merging and speed-perturbing datasets.
 - The same consideration *might* apply to the recording stuff, that it is too concrete.  We don't know what kinds formats and reading methods, or what simulation methods, we or others might want to use in future.  I'm thinking that maybe we could somehow make it more changeable/overridable?  I'm not sure of what mechanism to suggest here.  One possibility is to separate the metadata from the actual audio, so that the AudioSet has a mechanism whereby you can get metadata somehow, but the interface to retrieve the audio goes through AudioSet and just returns the float array in a standardized format without revealing much about where it came from.
 - With metadata: bear in mind that we may later need to add new metadata fields that we may not be anticipating now.  So perhaps we could avoid making any decisions that will pin us down to only a specified set of fields.   On the other hand, sometimes concreteness is a blessing, so I'm willing to argue about this point.

Also, having a default implementation of AudioSet is fine.  But let's be clear what is the standard supported interface of AudioSet (and of its mechanism for supplying metadata) and what is just the default implementation.

[Sorry, I'm having trouble with GitHub interface, apologies for dupes, the following is a small unrelated issue: ]

It would be nice to have a comment here mentioning that DummySet contains everything:

https://github.com/pzelasko/lhotse/blob/7555df605def57836c9454ae44aac95c504d86b0/lhotse/audio.py#L77

**Comment by pzelasko** [comment] 2020-04-26 17:48
> I get the impression that the AudioSource interface might assume that different channels will be located in different files? In general this won't be the case, often multiple channels will be interleaved in one file, like in the wav format.

I might have not documented that very well yet, but the idea is that `AudioSource` can specify input of file type which has multiple `channel_ids` (it's a list in the YAML). The code as is should correctly load multi-channel input, and it should also work with providing specific channels via `load_audio()` upon request. I'll add a relevant test for that.

BTW as a starting pointed I used `librosa`, which will handle a lot of existing audio formats out-of-the-box: https://librosa.github.io/librosa/ioformats.html#read-specific-formats

Also, note the `command` type of `AudioSource` which I added to retain the compatibility with `wav.scp` style of doing things - might be useful if we want to migrate existing Kaldi data dirs to this format (at least in the beginning).

> I think maybe the AudioSet interface, and its dependencies, are too concrete. (...)

That's a fair point. Let me think on it some more and get back to you. I was thinking of making the `AudioSource` the point where we can customize things (e.g. add reverberation/augmentations/transforms etc. on top of it), with maybe some convenience functions on the `AudioSet` and `Recording` that allow you to transform the whole set (conceptually an equivalent of `audio_set.map()`, which would yield a new `AudioSet` with modified `AudioSource`s or maybe even `Recording`s).

> With metadata: bear in mind that we may later need to add new metadata fields that we may not be anticipating now. So perhaps we could avoid making any decisions that will pin us down to only a specified set of fields. On the other hand, sometimes concreteness is a blessing, so I'm willing to argue about this point.

YAML supports optionality, we could modify the API to return `Optional[X]` instead of `X` in property accessors (e.g. if we add a new metadata item `codec`, we make `audio_set.codec('recording-id-1')` return `None` for "older" `AudioSet`s that do not have this property). I don't have a strong opinion whether it's the right call, but it seems reasonable, and e.g. protobuf does the same thing.

> It would be nice to have a comment here mentioning that DummySet contains everything:

Will do.

**Comment by danpovey** [comment] 2020-04-27 04:17
Regarding "I was thinking of making the AudioSource the point where we can customize things (e.g. add reverberation/augmentations/transforms etc. on top of it)"...  so I assume we're not just talking about command-line things here?  Some things would be more natural to do at the Python level.  One reason I feel that AudioSet might be a more natural place to do it is that it might interact better with randomness.. e.g. could in some cases be different  each time you iterate through it (like adding different random noises or reverberation, or, say, could add noise with a fixed probability).  But perhaps that could be done with AudioSource too?

**Comment by danpovey** [comment] 2020-04-27 04:17
Please invite @jtrmal if you haven't already.. would be nice to get his comments on this stuff.

**Comment by jtrmal** [comment] 2020-04-27 12:08
My feeling is we could just specify interface (has to have, say, "chunk
iterator", function len()... whatever). That is quite common in Python --
for example, they say that the given function expects "file-like" object.
Having a class hierarchy is more javistic approach, I feel.
I can imagine having AudioSource and on the top of it
TransformedAudioSoure that would be implementing the same interface and
being initialized by AudioSource. What would happen inside is
implementation-defined -- reverberation, noises and so on...
y.

**Comment by danpovey** [comment] 2020-04-27 12:18
Oh I see, so you are maybe saying just use duck typing so we can make
AudioSource a concrete implementation.

**Comment by jtrmal** [comment] 2020-04-27 12:19
yeah, pretty much that :)
y.

**Comment by danpovey** [comment] 2020-04-27 12:22
Yeah, seems reasonable.

**Comment by pzelasko** [comment] 2020-04-27 12:27
OK, so how about this - we add a data field 'transforms' in AudioSource, which in YAML looks like this:

```
- type: file
  channel_ids: [0]
  source: path/to/audio.wav
  transforms:
    - reverberate: {param1: 10, param2: 0.5, ...}
    - speed_perturb: {param1: 1.05,  ...}
```

and we apply these transforms lazily during `load_audio()` (with an option to disable them). We could then create a "transformed" `AudioSet` by calling either `.transform_all()` or `.transform_some(fraction=X)`. For example: `audio_set.reverberate_some(fraction=0.5, other_params=...)`. This function will propagate the transform to all AudioSources (maybe with some level of consistency on the `Recording` level, e.g. if an AudioSource is going to be reverberated, then all the other ones for a given recording will be too).

We could either control the randomness by creating a new transformed `AudioSet` for each epoch, or maybe - simpler - by setting the random seed to a different value (then we have exactly the same transforms for each `AudioSource`, but different output. The advantage of the second approach is that when we create such manifest and decide to share it, it's very reproducible - the transforms used are part of the dataset itself (but can be disabled). On the other hand, the first one is more flexible and maybe more useful for training.

**Comment by danpovey** [comment] 2020-04-27 12:35
Hm.  It's not what I had in mind, but it seems OK to me. Let's see what
Yenda thinks.  Bear in mind that if we are adding recordings of noise, we'd
need a source for that.  I guess I had in mind a more hierarchical
structure where it was done at the python script level rather than in the
manifest, e.g. it would load an object that adds noise and reverberation
and applies that to the dataset somehow.  And maybe that noise+reverb
object would have its own manifest.  But we don't have to set this in stone
now, we can just do something and then play around and see what we like.

**Comment by danpovey** [comment] 2020-04-27 12:36
I see the reproducibility advantage of what you are saying.  I suppose my
fear  is that as we add features or options, they all go in the yaml file
as extra fields and gradually make that class too complicated.  Whereas if
they were separate classes it's more, kind of, compositional.

**Comment by pzelasko** [comment] 2020-04-27 12:38
Makes sense. I see the risk of the files becoming too bloated. Let's start
with the more compositional approach and see what happens.

pon., 27 kwi 2020, 08:36 użytkownik Daniel Povey <notifications@github.com>
napisał:

> I see the reproducibility advantage of what you are saying. I suppose my
> fear is that as we add features or options, they all go in the yaml file
> as extra fields and gradually make that class too complicated. Whereas if
> they were separate classes it's more, kind of, compositional.
>

**Comment by jtrmal** [comment] 2020-04-27 12:44
Actually, my feeling is that I would prefer the factorized approach as
well...

On the longer-term, it would be nice to have say "ReplayManifest" that
would be generated automatically by the class hierarchy and could be saved
and executed next time for reproducibility. It does not have to be very
human-friendly.
I would feel most of the things normally will want to be randomized and the
reproducibility we could use the replay manifest (as an
orthogonal/additional feature)
y.

**Comment by pzelasko** [comment] 2020-06-22 14:17
I think the `AudioSet`/`Recording`/`AudioSource` interfaces should be pretty stable going forward, so I'm closing the issue. Feel free to re-open or create a new one if I missed something.

**Closed by pzelasko** 2020-06-22 14:17 UTC
